name: omko-admin
services:
- name: omko-admin-web
  github:
    repo: donelias/omko_admin
    branch: develop
  build_command: composer install && npm install && npm run build
  run_command: vendor/bin/heroku-php-apache2 public/
  envs:
  - key: APP_ENV
    value: production
  - key: APP_DEBUG
    value: "false"
  - key: APP_KEY
    scope: RUN_AND_BUILD_TIME
  - key: LOG_CHANNEL
    value: stack
  - key: CACHE_DRIVER
    value: database
  - key: SESSION_DRIVER
    value: database
  - key: QUEUE_CONNECTION
    value: database
  - key: DB_CONNECTION
    value: mysql
  - key: DB_HOST
    scope: RUN_TIME
  - key: DB_PORT
    scope: RUN_TIME
    value: "3306"
  - key: DB_DATABASE
    scope: RUN_TIME
  - key: DB_USERNAME
    scope: RUN_TIME
  - key: DB_PASSWORD
    scope: RUN_TIME
  http_port: 8080
  health_check:
    http_path: /
  source_dir: ./

databases:
- name: omko-db
  engine: MYSQL
  version: "8"

