<?php

$config = [
    'dashboard' => ['read'],
    'facility' => ['create', 'read', 'update', 'delete'],
    'categories' => ['create', 'read', 'update', 'delete'],
    'near_by_places' => ['create', 'read', 'update', 'delete'],
    'customer' => ['create', 'read', 'update', 'delete'],
    'verify_customer_form' => ['read', 'create', 'update', 'delete'],
    'approve_agent_verification' => ['read', 'update'],
    'property' => ['create', 'read', 'update', 'delete'],
    'city_images' => ['read', 'update', 'delete'],
    'project' => ['create', 'read', 'update', 'delete'],
    'report_reason' => ['create', 'read', 'update', 'delete'],
    'user_reports' => ['read'],
    'users_inquiries' => ['read'],
    'chat' => ['create', 'read'],
    'slider' => ['create', 'read', 'update', 'delete'],
    'article' => ['create', 'read', 'update', 'delete'],
    'advertisement' => ['read', 'update'],
    'package-feature' => ['read', 'update'],
    'package' => ['create', 'read', 'update', 'delete'],
    'user_package' => ['read'],
    'payment' => ['read'],
    'calculator' => ['read'],
    'faqs' => ['create', 'read', 'update', 'delete'],
    'users_accounts' => ['create', 'read', 'update'],
    'about_us' => ['read', 'update'],
    'privacy_policy' => ['read', 'update'],
    'terms_conditions' => ['read', 'update'],
    'language' => ['create', 'read', 'update', 'delete'],
    'system_settings' => ['read', 'update'],
    'app_settings' => ['read', 'update'],
    'web_settings' => ['read', 'update'],
    'firebase_settings' => ['read', 'update'],
    'notification_settings' => ['read', 'update'],
    'email_configurations' => ['read', 'update'],
    'email_templates' => ['read', 'update'],
    'admin_appointment_preferences' => ['read', 'update'],
    'admin_appointment_schedules' => ['read', 'update', 'delete'],
    'appointment_management' => ['read', 'update', 'delete'],
    'appointment_reports' => ['read', 'update'],
    'system_update' => ['read', 'update'],
    'notification' => ['read', 'create', 'delete'],
    'homepage-sections' => ['create', 'read', 'update', 'delete'],
    'seo_settings' => ['read', 'create', 'update', 'delete'],
    'ad-banners' => ['create', 'read', 'update', 'delete'],
    'assign_package' => ['read', 'update'],
    'watermark_settings' => ['read', 'update'],
    'gemini_settings' => ['read', 'update'],
    'payment_gateway_settings' => ['read', 'update'],
    'demo_data' => ['read', 'update'],
];

return $config;
